'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Fieldset as Base } from '@base-ui/react/fieldset'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-fieldset'))()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
}
export const Legend: typeof Base.Legend = /*#__PURE__*/ (() => wrapPart(Base.Legend, 'nave-base-ui-legend'))()
export declare namespace Legend {
  export type State = Base.Legend.State
  export type Props = Base.Legend.Props
}
