'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Tabs as Base } from '@base-ui/react/tabs'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type Orientation = Base.Root.Orientation
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Tab: typeof Base.Tab = /*#__PURE__*/ (() => wrapPart(Base.Tab, 'nave-base-ui-tab'))()
export declare namespace Tab {
  export type Value = Base.Tab.Value
  export type ActivationDirection = Base.Tab.ActivationDirection
  export type Position = Base.Tab.Position
  export type Size = Base.Tab.Size
  export type Metadata = Base.Tab.Metadata
  export type State = Base.Tab.State
  export type Props = Base.Tab.Props
}
export const Indicator: typeof Base.Indicator = /*#__PURE__*/ (() => wrapPart(Base.Indicator, 'nave-base-ui-tab-indicator'))()
export declare namespace Indicator {
  export type State = Base.Indicator.State
  export type Props = Base.Indicator.Props
}
export const Panel: typeof Base.Panel = /*#__PURE__*/ (() => Base.Panel)()
export declare namespace Panel {
  export type Metadata = Base.Panel.Metadata
  export type State = Base.Panel.State
  export type Props = Base.Panel.Props
}
export const List: typeof Base.List = /*#__PURE__*/ (() => wrapPart(Base.List, 'nave-base-ui-tab-list'))()
export declare namespace List {
  export type State = Base.List.State
  export type Props = Base.List.Props
}
