'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Toggle as Base } from '@base-ui/react/toggle'

import { wrapSizePart, type SizeProps } from '../part.ts'

export const Toggle: <TValue extends string>(props: Omit<Base.Props<TValue>, 'ref'> & RefAttributes<HTMLButtonElement> & SizeProps) => ReactElement = /*#__PURE__*/ (() => wrapSizePart(Base, 'nave-base-ui-toggle'))()
export declare namespace Toggle {
  export type State = Base.State
  export type Props<TValue extends string = string> = Base.Props<TValue> & SizeProps
  export type ChangeEventReason = Base.ChangeEventReason
  export type ChangeEventDetails = Base.ChangeEventDetails
}
