'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Accordion as Base } from '@base-ui/react/accordion'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type Value<TValue = any> = Base.Root.Value<TValue>
  export type State<TValue = any> = Base.Root.State<TValue>
  export type Props<TValue = any> = Base.Root.Props<TValue>
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Item: typeof Base.Item = /*#__PURE__*/ (() => wrapPart(Base.Item, 'nave-base-ui-accordion-item'))()
export declare namespace Item {
  export type State = Base.Item.State
  export type Props = Base.Item.Props
  export type ChangeEventReason = Base.Item.ChangeEventReason
  export type ChangeEventDetails = Base.Item.ChangeEventDetails
}
export const Header: typeof Base.Header = /*#__PURE__*/ (() => wrapPart(Base.Header, 'nave-base-ui-accordion-header'))()
export declare namespace Header {
  export type State = Base.Header.State
  export type Props = Base.Header.Props
}
export const Trigger: typeof Base.Trigger = /*#__PURE__*/ (() => wrapPart(Base.Trigger, 'nave-base-ui-disclosure-trigger nave-base-ui-disclosure-icon'))()
export declare namespace Trigger {
  export type State = Base.Trigger.State
  export type Props = Base.Trigger.Props
}
export const Panel: typeof Base.Panel = /*#__PURE__*/ (() => wrapPart(Base.Panel, 'nave-base-ui-accordion-panel'))()
export declare namespace Panel {
  export type State = Base.Panel.State
  export type Props = Base.Panel.Props
}
