'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Dialog as Base } from '@base-ui/react/dialog'

import { wrapPart, wrapVariantPart, type VariantProps } from '../part.ts'

export const Backdrop: typeof Base.Backdrop = /*#__PURE__*/ (() => Base.Backdrop)()
export declare namespace Backdrop {
  export type Props = Base.Backdrop.Props
  export type State = Base.Backdrop.State
}
export const Close: (props: Omit<Base.Close.Props, 'ref'> & RefAttributes<HTMLButtonElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base.Close, 'nave-base-ui-button'))()
export declare namespace Close {
  export type Props = Base.Close.Props & VariantProps
  export type State = Base.Close.State
}
export const Description: typeof Base.Description = /*#__PURE__*/ (() => wrapPart(Base.Description, 'nave-base-ui-description'))()
export declare namespace Description {
  export type Props = Base.Description.Props
  export type State = Base.Description.State
}
export const Popup: typeof Base.Popup = /*#__PURE__*/ (() => wrapPart(Base.Popup, 'nave-base-ui-dialog-popup'))()
export declare namespace Popup {
  export type Props = Base.Popup.Props
  export type State = Base.Popup.State
}
export const Portal: typeof Base.Portal = /*#__PURE__*/ (() => Base.Portal)()
export declare namespace Portal {
  export type State = Base.Portal.State
  export type Props = Base.Portal.Props
}
export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props<Payload = unknown> = Base.Root.Props<Payload>
  export type Actions = Base.Root.Actions
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Viewport: typeof Base.Viewport = /*#__PURE__*/ (() => Base.Viewport)()
export declare namespace Viewport {
  export type State = Base.Viewport.State
  export type Props = Base.Viewport.Props
}
export const Title: typeof Base.Title = /*#__PURE__*/ (() => wrapPart(Base.Title, 'nave-base-ui-title'))()
export declare namespace Title {
  export type Props = Base.Title.Props
  export type State = Base.Title.State
}
export const Trigger: <Payload>(props: Omit<Base.Trigger.Props<Payload>, 'ref'> & RefAttributes<HTMLElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base.Trigger, 'nave-base-ui-button'))()
export declare namespace Trigger {
  export type Props<Payload = unknown> = Base.Trigger.Props<Payload> & VariantProps
  export type State = Base.Trigger.State
}
export const createHandle: typeof Base.createHandle = /*#__PURE__*/ (() => Base.createHandle)()
export const Handle: typeof Base.Handle = /*#__PURE__*/ (() => Base.Handle)()
export type Handle<Payload> = Base.Handle<Payload>
