'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Radio as Base } from '@base-ui/react/radio'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-radio'))()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props<TValue = any> = Base.Root.Props<TValue>
}
export const Indicator: typeof Base.Indicator = /*#__PURE__*/ (() => wrapPart(Base.Indicator, 'nave-base-ui-radio-indicator'))()
export declare namespace Indicator {
  export type Props = Base.Indicator.Props
  export type State = Base.Indicator.State
}
