'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Button as Base } from '@base-ui/react/button'

import { wrapVariantPart, type VariantProps } from '../part.ts'

export const Button: (props: Omit<Base.Props, 'ref'> & RefAttributes<HTMLElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base, 'nave-base-ui-button'))()
export declare namespace Button {
  export type State = Base.State
  export type Props = Base.Props & VariantProps
}
