'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { NumberField as Base } from '@base-ui/react/number-field'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
  export type CommitEventReason = Base.Root.CommitEventReason
  export type CommitEventDetails = Base.Root.CommitEventDetails
}
export const Group: typeof Base.Group = /*#__PURE__*/ (() => wrapPart(Base.Group, 'nave-base-ui-number-field-group'))()
export declare namespace Group {
  export type State = Base.Group.State
  export type Props = Base.Group.Props
}
export const Increment: typeof Base.Increment = /*#__PURE__*/ (() => wrapPart(Base.Increment, 'nave-base-ui-number-field-stepper'))()
export declare namespace Increment {
  export type State = Base.Increment.State
  export type Props = Base.Increment.Props
}
export const Decrement: typeof Base.Decrement = /*#__PURE__*/ (() => wrapPart(Base.Decrement, 'nave-base-ui-number-field-stepper'))()
export declare namespace Decrement {
  export type State = Base.Decrement.State
  export type Props = Base.Decrement.Props
}
export const Input: typeof Base.Input = /*#__PURE__*/ (() => wrapPart(Base.Input, 'nave-base-ui-number-field-input'))()
export declare namespace Input {
  export type State = Base.Input.State
  export type Props = Base.Input.Props
}
export const ScrubArea: typeof Base.ScrubArea = /*#__PURE__*/ (() => wrapPart(Base.ScrubArea, 'nave-base-ui-number-field-scrub-area'))()
export declare namespace ScrubArea {
  export type State = Base.ScrubArea.State
  export type Props = Base.ScrubArea.Props
}
export const ScrubAreaCursor: typeof Base.ScrubAreaCursor = /*#__PURE__*/ (() => Base.ScrubAreaCursor)()
export declare namespace ScrubAreaCursor {
  export type State = Base.ScrubAreaCursor.State
  export type Props = Base.ScrubAreaCursor.Props
}
