'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Input as Base } from '@base-ui/react/input'

import { wrapPart } from '../part.ts'

export const Input: typeof Base = /*#__PURE__*/ (() => wrapPart(Base, 'nave-base-ui-input'))()
export declare namespace Input {
  export type Props = Base.Props
  export type State = Base.State
  export type ChangeEventReason = Base.ChangeEventReason
  export type ChangeEventDetails = Base.ChangeEventDetails
}
