/**
 * AC-token-build-30 covers: R30.
 *
 * R30 is safety-critical-adjacent (section E, "the fences") and its own text says what must
 * NOT happen: "this rides as prose... prose is exactly what the other two licensing predicates
 * [R28, R29] have instruments instead of." `src/theming/third-party-provenance.ts` is that
 * instrument. Two halves, matching the AC's own two `Given`s:
 *
 * 1. Every R6 artifact traces to first-party source (shares its scan with
 *    `AC-token-build-28`'s generator half; this block names its own AC and does not restate
 *    R28's compiled-JS half).
 * 2. The ROUTING OBLIGATION exists as a checkable fact, not only as spec prose — the AC's own
 *    words: "this scenario asserts the ROUTING obligation exists, not that any instance has
 *    been cleared." Nothing here clears an instance; nothing here is the accessibility/licensing
 *    steward's to clear.
 */
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import {
  findThirdPartyResidue,
  findUnattributedHeader,
  R6_CONSUMER_ARTIFACTS,
  THIRD_PARTY_TEXT_ROUTING_POLICY,
} from '../../src/theming/third-party-provenance.ts'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const DIST_DIR = path.resolve(HERE, '../../dist')

describe('AC-token-build-30 covers: R30 (provenance — every R6 artifact traces to first-party source)', () => {
  it('no R6 artifact carries a byte traceable to a third-party source (style-dictionary residue, or an unattributed generated-file header)', () => {
    const artifacts = R6_CONSUMER_ARTIFACTS.map((name) => ({
      path: name,
      content: readFileSync(path.join(DIST_DIR, name), 'utf8'),
    }))
    expect(findThirdPartyResidue(artifacts)).toEqual([])
    const headerBearing = artifacts.filter(
      (a) => a.path.endsWith('.css') || a.path.endsWith('.js') || a.path.endsWith('.d.ts'),
    )
    expect(findUnattributedHeader(headerBearing)).toEqual([])
  })

  it('the scan actually catches a poisoned fixture (both directions of the check are exercised, not only the passing one)', () => {
    const poisonedByResidue = [{ path: 'tokens.css', content: '/* built with style-dictionary */' }]
    expect(findThirdPartyResidue(poisonedByResidue)).toEqual(['tokens.css'])

    const poisonedByHeader = [{ path: 'tokens.js', content: '/* Generated by SomeOtherTool */' }]
    expect(findUnattributedHeader(poisonedByHeader)).toEqual(['tokens.js'])
  })
})

describe('AC-token-build-30 covers: R30 (the routing obligation exists as a checkable fact)', () => {
  it('names the licence-review route, "before publication", and the three named shapes — as examples, never an enumeration', () => {
    const policy = THIRD_PARTY_TEXT_ROUTING_POLICY
    // The persona name this constant used to carry (a reviewer's role label) compiled
    // into a published tarball under R8 (dist/lib preserving comments AND runtime string
    // literals), which no reader outside the project can resolve. Replaced with a
    // self-sufficient description of the same routing obligation.
    expect(policy).toMatch(/licence review/)
    expect(policy).toMatch(/before publication/)
    // The three shapes R30 names AS EXAMPLES ("as examples and not as an enumeration"):
    expect(policy).toMatch(/vendor/i)
    expect(policy.toLowerCase()).toContain('inline')
    expect(policy).toMatch(/third[- ]party/i)
    // Never phrased as a closed list — a prohibition written as a list defaults to permitted.
    expect(policy).toMatch(/not an enumeration/i)
    expect(policy).toMatch(/noExternal/)
  })

  it('is a real exported value, though no caller outside this test references it today', () => {
    expect(existsSync(path.resolve(HERE, '../../src/theming/third-party-provenance.ts'))).toBe(true)
    expect(typeof THIRD_PARTY_TEXT_ROUTING_POLICY).toBe('string')
    expect(THIRD_PARTY_TEXT_ROUTING_POLICY.length).toBeGreaterThan(0)
  })
})
