'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Form as Base } from '@base-ui/react/form'

export const Form: typeof Base = /*#__PURE__*/ (() => Base)()
export declare namespace Form {
  export type Props<FormValues extends Record<string, any> = Record<string, any>> = Base.Props<FormValues>
  export type State = Base.State
  export type Actions = Base.Actions
  export type ValidationMode = Base.ValidationMode
  export type SubmitEventReason = Base.SubmitEventReason
  export type SubmitEventDetails = Base.SubmitEventDetails
  export type Values<FormValues extends Record<string, any> = Record<string, any>> = Base.Values<FormValues>
}
