'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { ToggleGroup as Base } from '@base-ui/react/toggle-group'

import { wrapPart } from '../part.ts'

export const ToggleGroup: typeof Base = /*#__PURE__*/ (() => wrapPart(Base, 'nave-base-ui-toggle-group'))()
export declare namespace ToggleGroup {
  export type State = Base.State
  export type Props<Value extends string = string> = Base.Props<Value>
  export type ChangeEventReason = Base.ChangeEventReason
  export type ChangeEventDetails = Base.ChangeEventDetails
}
