'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Select as Base } from '@base-ui/react/select'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type Props<Value, Multiple extends boolean | undefined = false> = Base.Root.Props<Value, Multiple>
  export type State = Base.Root.State
  export type Actions = Base.Root.Actions
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Label: typeof Base.Label = /*#__PURE__*/ (() => wrapPart(Base.Label, 'nave-base-ui-label'))()
export declare namespace Label {
  export type State = Base.Label.State
  export type Props = Base.Label.Props
}
export const Trigger: typeof Base.Trigger = /*#__PURE__*/ (() => wrapPart(Base.Trigger, 'nave-base-ui-select-trigger'))()
export declare namespace Trigger {
  export type State = Base.Trigger.State
  export type Props = Base.Trigger.Props
}
export const Value: typeof Base.Value = /*#__PURE__*/ (() => wrapPart(Base.Value, 'nave-base-ui-select-value'))()
export declare namespace Value {
  export type State = Base.Value.State
  export type Props = Base.Value.Props
}
export const Icon: typeof Base.Icon = /*#__PURE__*/ (() => wrapPart(Base.Icon, 'nave-base-ui-select-icon'))()
export declare namespace Icon {
  export type State = Base.Icon.State
  export type Props = Base.Icon.Props
}
export const Portal: typeof Base.Portal = /*#__PURE__*/ (() => Base.Portal)()
export declare namespace Portal {
  export type State = Base.Portal.State
  export type Props = Base.Portal.Props
}
export const Backdrop: typeof Base.Backdrop = /*#__PURE__*/ (() => Base.Backdrop)()
export declare namespace Backdrop {
  export type State = Base.Backdrop.State
  export type Props = Base.Backdrop.Props
}
export const Positioner: typeof Base.Positioner = /*#__PURE__*/ (() => Base.Positioner)()
export declare namespace Positioner {
  export type State = Base.Positioner.State
  export type Props = Base.Positioner.Props
}
export const Popup: typeof Base.Popup = /*#__PURE__*/ (() => wrapPart(Base.Popup, 'nave-base-ui-list-popup'))()
export declare namespace Popup {
  export type Props = Base.Popup.Props
  export type State = Base.Popup.State
}
export const List: typeof Base.List = /*#__PURE__*/ (() => Base.List)()
export declare namespace List {
  export type Props = Base.List.Props
  export type State = Base.List.State
}
export const Item: typeof Base.Item = /*#__PURE__*/ (() => wrapPart(Base.Item, 'nave-base-ui-item'))()
export declare namespace Item {
  export type State = Base.Item.State
  export type Props = Base.Item.Props
}
export const ItemIndicator: typeof Base.ItemIndicator = /*#__PURE__*/ (() => Base.ItemIndicator)()
export declare namespace ItemIndicator {
  export type State = Base.ItemIndicator.State
  export type Props = Base.ItemIndicator.Props
}
export const ItemText: typeof Base.ItemText = /*#__PURE__*/ (() => Base.ItemText)()
export declare namespace ItemText {
  export type State = Base.ItemText.State
  export type Props = Base.ItemText.Props
}
export const Arrow: typeof Base.Arrow = /*#__PURE__*/ (() => wrapPart(Base.Arrow, 'nave-base-ui-arrow'))()
export declare namespace Arrow {
  export type State = Base.Arrow.State
  export type Props = Base.Arrow.Props
}
export const ScrollDownArrow: typeof Base.ScrollDownArrow = /*#__PURE__*/ (() => Base.ScrollDownArrow)()
export declare namespace ScrollDownArrow {
  export type State = Base.ScrollDownArrow.State
  export type Props = Base.ScrollDownArrow.Props
}
export const ScrollUpArrow: typeof Base.ScrollUpArrow = /*#__PURE__*/ (() => Base.ScrollUpArrow)()
export declare namespace ScrollUpArrow {
  export type State = Base.ScrollUpArrow.State
  export type Props = Base.ScrollUpArrow.Props
}
export const Group: typeof Base.Group = /*#__PURE__*/ (() => Base.Group)()
export declare namespace Group {
  export type State = Base.Group.State
  export type Props = Base.Group.Props
}
export const GroupLabel: typeof Base.GroupLabel = /*#__PURE__*/ (() => wrapPart(Base.GroupLabel, 'nave-base-ui-group-label'))()
export declare namespace GroupLabel {
  export type State = Base.GroupLabel.State
  export type Props = Base.GroupLabel.Props
}
export const Separator: typeof Base.Separator = /*#__PURE__*/ (() => wrapPart(Base.Separator, 'nave-base-ui-separator'))()
export declare namespace Separator {
  export type Props = Base.Separator.Props
  export type State = Base.Separator.State
}
