'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Tooltip as Base } from '@base-ui/react/tooltip'

import { wrapPart, wrapVariantPart, type VariantProps } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props<Payload = unknown> = Base.Root.Props<Payload>
  export type Actions = Base.Root.Actions
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Trigger: <Payload>(props: Omit<Base.Trigger.Props<Payload>, 'ref'> & RefAttributes<HTMLElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base.Trigger, 'nave-base-ui-button'))()
export declare namespace Trigger {
  export type State = Base.Trigger.State
  export type Props<Payload = unknown> = Base.Trigger.Props<Payload> & VariantProps
}
export const Portal: typeof Base.Portal = /*#__PURE__*/ (() => Base.Portal)()
export declare namespace Portal {
  export type State = Base.Portal.State
  export type Props = Base.Portal.Props
}
export const Positioner: typeof Base.Positioner = /*#__PURE__*/ (() => Base.Positioner)()
export declare namespace Positioner {
  export type State = Base.Positioner.State
  export type Props = Base.Positioner.Props
}
export const Popup: typeof Base.Popup = /*#__PURE__*/ (() => wrapPart(Base.Popup, 'nave-base-ui-tooltip-popup'))()
export declare namespace Popup {
  export type State = Base.Popup.State
  export type Props = Base.Popup.Props
}
export const Arrow: typeof Base.Arrow = /*#__PURE__*/ (() => wrapPart(Base.Arrow, 'nave-base-ui-arrow'))()
export declare namespace Arrow {
  export type State = Base.Arrow.State
  export type Props = Base.Arrow.Props
}
export const Provider: typeof Base.Provider = /*#__PURE__*/ (() => Base.Provider)()
export declare namespace Provider {
  export type State = Base.Provider.State
  export type Props = Base.Provider.Props
}
export const Viewport: typeof Base.Viewport = /*#__PURE__*/ (() => Base.Viewport)()
export declare namespace Viewport {
  export type Props = Base.Viewport.Props
  export type State = Base.Viewport.State
}
export const createHandle: typeof Base.createHandle = /*#__PURE__*/ (() => Base.createHandle)()
export const Handle: typeof Base.Handle = /*#__PURE__*/ (() => Base.Handle)()
export type Handle<Payload> = Base.Handle<Payload>
