'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { RadioGroup as Base } from '@base-ui/react/radio-group'

import { wrapPart } from '../part.ts'

export const RadioGroup: typeof Base = /*#__PURE__*/ (() => wrapPart(Base, 'nave-base-ui-choice-group'))()
export declare namespace RadioGroup {
  export type State = Base.State
  export type Props<TValue = any> = Base.Props<TValue>
  export type ChangeEventReason = Base.ChangeEventReason
  export type ChangeEventDetails = Base.ChangeEventDetails
}
