'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Checkbox as Base } from '@base-ui/react/checkbox'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-checkbox'))()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Indicator: typeof Base.Indicator = /*#__PURE__*/ (() => wrapPart(Base.Indicator, 'nave-base-ui-checkbox-indicator'))()
export declare namespace Indicator {
  export type State = Base.Indicator.State
  export type Props = Base.Indicator.Props
}
