'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Field as Base } from '@base-ui/react/field'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-field'))()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type Actions = Base.Root.Actions
}
export const Label: typeof Base.Label = /*#__PURE__*/ (() => wrapPart(Base.Label, 'nave-base-ui-label'))()
export declare namespace Label {
  export type State = Base.Label.State
  export type Props = Base.Label.Props
}
const FieldError: typeof Base.Error = /*#__PURE__*/ (() => wrapPart(Base.Error, 'nave-base-ui-field-error'))()
declare namespace FieldError {
  export type State = Base.Error.State
  export type Props = Base.Error.Props
}
export { FieldError as Error }
export const Description: typeof Base.Description = /*#__PURE__*/ (() => wrapPart(Base.Description, 'nave-base-ui-field-description'))()
export declare namespace Description {
  export type State = Base.Description.State
  export type Props = Base.Description.Props
}
export const Control: typeof Base.Control = /*#__PURE__*/ (() => wrapPart(Base.Control, 'nave-base-ui-input'))()
export declare namespace Control {
  export type State = Base.Control.State
  export type Props = Base.Control.Props
  export type ChangeEventReason = Base.Control.ChangeEventReason
  export type ChangeEventDetails = Base.Control.ChangeEventDetails
}
export const Validity: typeof Base.Validity = /*#__PURE__*/ (() => Base.Validity)()
export declare namespace Validity {
  export type State = Base.Validity.State
  export type Props = Base.Validity.Props
}
export const Item: typeof Base.Item = /*#__PURE__*/ (() => Base.Item)()
export declare namespace Item {
  export type State = Base.Item.State
  export type Props = Base.Item.Props
}
