'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { CheckboxGroup as Base } from '@base-ui/react/checkbox-group'

import { wrapPart } from '../part.ts'

export const CheckboxGroup: typeof Base = /*#__PURE__*/ (() => wrapPart(Base, 'nave-base-ui-choice-group'))()
export declare namespace CheckboxGroup {
  export type State = Base.State
  export type Props = Base.Props
  export type ChangeEventReason = Base.ChangeEventReason
  export type ChangeEventDetails = Base.ChangeEventDetails
}
