'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Menu as Base } from '@base-ui/react/menu'

import { wrapPart, wrapVariantPart, type VariantProps } from '../part.ts'

export const Arrow: typeof Base.Arrow = /*#__PURE__*/ (() => wrapPart(Base.Arrow, 'nave-base-ui-arrow'))()
export declare namespace Arrow {
  export type State = Base.Arrow.State
  export type Props = Base.Arrow.Props
}
export const Backdrop: typeof Base.Backdrop = /*#__PURE__*/ (() => Base.Backdrop)()
export declare namespace Backdrop {
  export type State = Base.Backdrop.State
  export type Props = Base.Backdrop.Props
}
export const CheckboxItem: typeof Base.CheckboxItem = /*#__PURE__*/ (() => wrapPart(Base.CheckboxItem, 'nave-base-ui-item'))()
export declare namespace CheckboxItem {
  export type State = Base.CheckboxItem.State
  export type Props = Base.CheckboxItem.Props
  export type ChangeEventReason = Base.CheckboxItem.ChangeEventReason
  export type ChangeEventDetails = Base.CheckboxItem.ChangeEventDetails
}
export const CheckboxItemIndicator: typeof Base.CheckboxItemIndicator = /*#__PURE__*/ (() => Base.CheckboxItemIndicator)()
export declare namespace CheckboxItemIndicator {
  export type Props = Base.CheckboxItemIndicator.Props
  export type State = Base.CheckboxItemIndicator.State
}
export const Group: typeof Base.Group = /*#__PURE__*/ (() => Base.Group)()
export declare namespace Group {
  export type Props = Base.Group.Props
  export type State = Base.Group.State
}
export const GroupLabel: typeof Base.GroupLabel = /*#__PURE__*/ (() => wrapPart(Base.GroupLabel, 'nave-base-ui-group-label'))()
export declare namespace GroupLabel {
  export type Props = Base.GroupLabel.Props
  export type State = Base.GroupLabel.State
}
export const Item: typeof Base.Item = /*#__PURE__*/ (() => wrapPart(Base.Item, 'nave-base-ui-item'))()
export declare namespace Item {
  export type State = Base.Item.State
  export type Props = Base.Item.Props
}
export const LinkItem: typeof Base.LinkItem = /*#__PURE__*/ (() => wrapPart(Base.LinkItem, 'nave-base-ui-item'))()
export declare namespace LinkItem {
  export type State = Base.LinkItem.State
  export type Props = Base.LinkItem.Props
}
export const Popup: typeof Base.Popup = /*#__PURE__*/ (() => wrapPart(Base.Popup, 'nave-base-ui-list-popup'))()
export declare namespace Popup {
  export type Props = Base.Popup.Props
  export type State = Base.Popup.State
}
export const Portal: typeof Base.Portal = /*#__PURE__*/ (() => Base.Portal)()
export declare namespace Portal {
  export type State = Base.Portal.State
  export type Props = Base.Portal.Props
}
export const Positioner: typeof Base.Positioner = /*#__PURE__*/ (() => Base.Positioner)()
export declare namespace Positioner {
  export type State = Base.Positioner.State
  export type Props = Base.Positioner.Props
}
export const RadioGroup: typeof Base.RadioGroup = /*#__PURE__*/ (() => Base.RadioGroup)()
export declare namespace RadioGroup {
  export type Props = Base.RadioGroup.Props
  export type State = Base.RadioGroup.State
  export type ChangeEventReason = Base.RadioGroup.ChangeEventReason
  export type ChangeEventDetails = Base.RadioGroup.ChangeEventDetails
}
export const RadioItem: typeof Base.RadioItem = /*#__PURE__*/ (() => wrapPart(Base.RadioItem, 'nave-base-ui-item'))()
export declare namespace RadioItem {
  export type State = Base.RadioItem.State
  export type Props = Base.RadioItem.Props
}
export const RadioItemIndicator: typeof Base.RadioItemIndicator = /*#__PURE__*/ (() => Base.RadioItemIndicator)()
export declare namespace RadioItemIndicator {
  export type Props = Base.RadioItemIndicator.Props
  export type State = Base.RadioItemIndicator.State
}
export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props<Payload = unknown> = Base.Root.Props<Payload>
  export type Actions = Base.Root.Actions
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
  export type Orientation = Base.Root.Orientation
}
export const SubmenuRoot: typeof Base.SubmenuRoot = /*#__PURE__*/ (() => Base.SubmenuRoot)()
export declare namespace SubmenuRoot {
  export type Props = Base.SubmenuRoot.Props
  export type State = Base.SubmenuRoot.State
  export type ChangeEventReason = Base.SubmenuRoot.ChangeEventReason
  export type ChangeEventDetails = Base.SubmenuRoot.ChangeEventDetails
}
export const Trigger: <Payload>(props: Omit<Base.Trigger.Props<Payload>, 'ref'> & RefAttributes<HTMLElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base.Trigger, 'nave-base-ui-button'))()
export declare namespace Trigger {
  export type Props<Payload = unknown> = Base.Trigger.Props<Payload> & VariantProps
  export type State = Base.Trigger.State
}
export const Viewport: typeof Base.Viewport = /*#__PURE__*/ (() => Base.Viewport)()
export declare namespace Viewport {
  export type Props = Base.Viewport.Props
  export type State = Base.Viewport.State
}
export const Separator: typeof Base.Separator = /*#__PURE__*/ (() => wrapPart(Base.Separator, 'nave-base-ui-separator'))()
export declare namespace Separator {
  export type Props = Base.Separator.Props
  export type State = Base.Separator.State
}
export const SubmenuTrigger: typeof Base.SubmenuTrigger = /*#__PURE__*/ (() => wrapPart(Base.SubmenuTrigger, 'nave-base-ui-item'))()
export declare namespace SubmenuTrigger {
  export type Props = Base.SubmenuTrigger.Props
  export type State = Base.SubmenuTrigger.State
}
export const Handle: typeof Base.Handle = /*#__PURE__*/ (() => Base.Handle)()
export type Handle<Payload> = Base.Handle<Payload>
export const createHandle: typeof Base.createHandle = /*#__PURE__*/ (() => Base.createHandle)()
