/**
 * Writes the wrapper modules of `src/`: for each v1 subpath, the module a consumer imports in place
 * of `@base-ui/react/<subpath>`. Every part of the component is exported as Base UI's own part,
 * wrapped with Nave's class where the roster styles it and passed through where it does not, and
 * every part keeps Base UI's type namespace (`Menu.Item.Props`, `Menu.Root.State`).
 *
 * The parts, their kinds and their type namespaces are read from the installed Base UI's
 * declarations, so the wrappers cannot name a part Base UI does not have or miss one it does; the
 * roster says only which parts are styled. Run: node scripts/generate-wrappers.ts
 *
 * `generateWrappers` is exported for the tests; the file-writing driver stays behind `isMain`.
 */
import type { AtomName } from '@navecss/core/atoms'

import { toClassName } from '@navecss/core/atoms'
import { mkdirSync, realpathSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { PartTypes, SubpathTypes } from './wrappers/read-types.ts'
import type { StyledPart } from './wrappers/roster.ts'

import { readBaseUiTypes } from './wrappers/read-types.ts'
import { styledParts } from './wrappers/roster.ts'
import { SINGLE_COMPONENT, SUBPATHS, topName } from './wrappers/subpaths.ts'

const SRC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src')

const isMain =
  process.argv[1] !== undefined &&
  realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1])

const NOTICE =
  '// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.'

// The component's own name is exported from the parts module as well as by the star re-export of
// Base UI's types, and TypeScript lets the named export win; the lint rule does not know that.
// Part names that are also JavaScript globals (`Field.Error`).
const GLOBAL_NAMES: ReadonlySet<string> = new Set(['Error'])

const SINGLE_NOTICE =
  '/* eslint-disable import-x/export -- the named export wins over the star re-export, as TypeScript has it */\n'

const classNameOf = (styled: StyledPart): string =>
  styled.atoms.map((atom) => toClassName(atom as AtomName)).join(' ')

const generics = (names: readonly string[]): string =>
  names.length === 0 ? '' : `<${names.join(', ')}>`

/**
 * The value a part is exported as: wrapped where the roster styles it, or Base UI's own. Either way
 * it is a pure call of a function that reads the part inside it, so a bundler drops it when nothing
 * uses it: a plain property, or an argument read outside the call, would count as a side effect
 * and keep the part.
 */
const valueOf = (
  name: string,
  reference: string,
  styled: StyledPart | undefined,
  part: PartTypes,
): string => {
  if (styled === undefined) {
    return `export const ${name}: typeof ${reference} = /*#__PURE__*/ (() => ${reference})()`
  }
  const className = classNameOf(styled)
  if (styled.variants === undefined) {
    return `export const ${name}: typeof ${reference} = /*#__PURE__*/ (() => wrapPart(${reference}, '${className}'))()`
  }
  const wrapper = styled.variants === 'variant' ? 'wrapVariantPart' : 'wrapSizePart'
  return `export const ${name}: ${variantType(reference, part, styled)} = /*#__PURE__*/ (() => ${wrapper}(${reference}, '${className}'))()`
}

/**
 * The type of a part of the Button family: Base UI's own `Props` for the part, with its `ref`
 * typed by the element the part declares, and the added props. Spelled out from the public
 * namespace instead of read off the part, because the type read off a part names Base UI's
 * internal modules and freezes the shape of one version.
 */
const variantType = (reference: string, part: PartTypes, styled: StyledPart): string => {
  const props = part.members.find((member) => member.name === 'Props')
  const added = styled.variants === 'variant' ? 'VariantProps' : 'SizeProps'
  const element = part.refElement ?? 'HTMLElement'
  const own = `Omit<${reference}.Props${generics(props?.arguments ?? [])}, 'ref'> & RefAttributes<${element}> & ${added}`
  const declared = part.callTypeParameters.length > 0 ? (props?.bare ?? []) : []
  return `${generics(declared)}(props: ${own}) => ReactElement`
}

const addedProps = (styled: StyledPart | undefined): string =>
  styled?.variants === undefined
    ? ''
    : ` & ${styled.variants === 'variant' ? 'VariantProps' : 'SizeProps'}`

/**
The type namespace of a part: each member Base UI's own, with the variant props added to `Props`.
 */
const namespaceOf = (
  name: string,
  reference: string,
  part: PartTypes,
  styled: StyledPart | undefined,
): string[] => {
  if (part.members.length === 0) {
    return []
  }
  const members = part.members.map((member) => {
    const extra = member.name === 'Props' ? addedProps(styled) : ''
    return `  export type ${member.name}${generics(member.parameters)} = ${reference}.${member.name}${generics(member.arguments)}${extra}`
  })
  return [`export declare namespace ${name} {`, ...members, '}']
}

const classOf = (name: string, reference: string, part: PartTypes): string[] =>
  part.kind === 'class'
    ? [
        `export type ${name}${generics(part.classParameters)} = ${reference}${generics(part.classParameters.map((parameter) => parameter.split(/\s/, 1)[0] ?? parameter))}`,
      ]
    : []

const partBlock = (
  subpath: string,
  part: PartTypes,
  isSingle: boolean,
  used: Set<string>,
): string[] => {
  const top = topName(subpath)
  const name = isSingle ? top : part.name
  const reference = isSingle ? 'Base' : `Base.${part.name}`
  const styled = styledParts[isSingle ? top : `${top}.${part.name}`]
  if (styled !== undefined) {
    used.add(isSingle ? top : `${top}.${part.name}`)
  }
  const lines = (local: string): string[] => [
    valueOf(local, reference, styled, part),
    ...classOf(local, reference, part),
    ...namespaceOf(local, reference, part, styled),
  ]
  if (!GLOBAL_NAMES.has(name)) {
    return lines(name)
  }
  // Declaring a variable called `Error` shadows the global, so it is declared under another name
  // and exported as `Error`.
  const local = `${top}${name}`
  return [
    ...lines(local).map((line) => line.replace(/^export /, '')),
    `export { ${local} as ${name} }`,
  ]
}

const helpersUsed = (body: string): string[] =>
  ['wrapPart', 'wrapSizePart', 'wrapVariantPart'].filter((helper) => body.includes(`${helper}(`))

const typesUsed = (body: string): string[] =>
  ['SizeProps', 'VariantProps'].filter((type) => body.includes(`& ${type}`))

const imports = (subpath: string, body: string): string => {
  const names = [...helpersUsed(body), ...typesUsed(body).map((type) => `type ${type}`)].join(', ')
  const react = ['ReactElement', 'RefAttributes'].filter((type) => body.includes(type))
  return [
    ...(react.length === 0 ? [] : [`import type { ${react.join(', ')} } from 'react'`]),
    `import { ${topName(subpath)} as Base } from '@base-ui/react/${subpath}'`,
    '',
    ...(names === '' ? [] : [`import { ${names} } from '../part.ts'`, '']),
  ].join('\n')
}

const generateSubpath = (types: SubpathTypes, used: Set<string>): Map<string, string> => {
  const { parts, subpath } = types
  const isSingle = SINGLE_COMPONENT.has(subpath)
  const body = parts.flatMap((part) => partBlock(subpath, part, isSingle, used)).join('\n')
  const reexport = `export type * from '@base-ui/react/${subpath}'`
  // A namespace of parts is exported as `Dialog`; a single component is exported by its own name,
  // which takes the place of the one the star re-export of Base UI's types would otherwise bring.
  const ownExport = isSingle
    ? `export { ${topName(subpath)} } from './parts.generated.ts'`
    : `export * as ${topName(subpath)} from './parts.generated.ts'`
  const index = `'use client'\n${isSingle ? SINGLE_NOTICE : ''}\n${ownExport}\n${reexport}\n`
  const generated = `'use client'\n${NOTICE}\n${imports(subpath, body)}\n${body}\n`
  return new Map([
    [`${subpath}/index.ts`, index],
    [`${subpath}/parts.generated.ts`, generated],
  ])
}

const rootModule = (): string =>
  `'use client'\n\n${SUBPATHS.map((subpath) => `export * from './${subpath}/index.ts'`)
    .toSorted((a, b) => a.localeCompare(b))
    .join('\n')}\n`

/**
 * Every file of `src/` this script writes, by path relative to `src/`. Throws when the roster names
 * a part the installed Base UI does not have.
 */
export const generateWrappers = (): Map<string, string> => {
  const used = new Set<string>()
  const files = new Map<string, string>()
  for (const types of readBaseUiTypes('current')) {
    for (const [file, text] of generateSubpath(types, used)) {
      files.set(file, text)
    }
  }
  const unknown = Object.keys(styledParts).filter((key) => !used.has(key))
  if (unknown.length > 0) {
    throw new Error(`the roster names parts Base UI does not have: ${unknown.join(', ')}`)
  }
  files.set('index.ts', rootModule())
  return files
}

if (isMain) {
  for (const [file, text] of generateWrappers()) {
    mkdirSync(path.dirname(path.join(SRC, file)), { recursive: true })
    writeFileSync(path.join(SRC, file), text)
  }
}
