'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Collapsible as Base } from '@base-ui/react/collapsible'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Trigger: typeof Base.Trigger = /*#__PURE__*/ (() => wrapPart(Base.Trigger, 'nave-base-ui-disclosure-trigger nave-base-ui-disclosure-icon'))()
export declare namespace Trigger {
  export type State = Base.Trigger.State
  export type Props = Base.Trigger.Props
}
export const Panel: typeof Base.Panel = /*#__PURE__*/ (() => wrapPart(Base.Panel, 'nave-base-ui-collapsible-panel'))()
export declare namespace Panel {
  export type State = Base.Panel.State
  export type Props = Base.Panel.Props
}
