'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import type { ReactElement, RefAttributes } from 'react'
import { Toolbar as Base } from '@base-ui/react/toolbar'

import { wrapPart, wrapVariantPart, type VariantProps } from '../part.ts'

export const Separator: typeof Base.Separator = /*#__PURE__*/ (() => wrapPart(Base.Separator, 'nave-base-ui-toolbar-separator'))()
export declare namespace Separator {
  export type State = Base.Separator.State
  export type Props = Base.Separator.Props
}
export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-toolbar'))()
export declare namespace Root {
  export type ItemMetadata = Base.Root.ItemMetadata
  export type Orientation = Base.Root.Orientation
  export type State = Base.Root.State
  export type Props = Base.Root.Props
}
export const Group: typeof Base.Group = /*#__PURE__*/ (() => wrapPart(Base.Group, 'nave-base-ui-toolbar-group'))()
export declare namespace Group {
  export type State = Base.Group.State
  export type Props = Base.Group.Props
}
export const Button: (props: Omit<Base.Button.Props, 'ref'> & RefAttributes<HTMLButtonElement> & VariantProps) => ReactElement = /*#__PURE__*/ (() => wrapVariantPart(Base.Button, 'nave-base-ui-button'))()
export declare namespace Button {
  export type State = Base.Button.State
  export type Props = Base.Button.Props & VariantProps
}
export const Link: typeof Base.Link = /*#__PURE__*/ (() => wrapPart(Base.Link, 'nave-base-ui-toolbar-link'))()
export declare namespace Link {
  export type State = Base.Link.State
  export type Props = Base.Link.Props
}
export const Input: typeof Base.Input = /*#__PURE__*/ (() => wrapPart(Base.Input, 'nave-base-ui-input'))()
export declare namespace Input {
  export type State = Base.Input.State
  export type Props = Base.Input.Props
}
