'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Switch as Base } from '@base-ui/react/switch'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => wrapPart(Base.Root, 'nave-base-ui-switch'))()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props = Base.Root.Props
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
}
export const Thumb: typeof Base.Thumb = /*#__PURE__*/ (() => wrapPart(Base.Thumb, 'nave-base-ui-switch-thumb'))()
export declare namespace Thumb {
  export type Props = Base.Thumb.Props
  export type State = Base.Thumb.State
}
