'use client'
// Generated by scripts/generate-wrappers.ts: change the roster or the generator, not this file.
import { Slider as Base } from '@base-ui/react/slider'

import { wrapPart } from '../part.ts'

export const Root: typeof Base.Root = /*#__PURE__*/ (() => Base.Root)()
export declare namespace Root {
  export type State = Base.Root.State
  export type Props<Value extends number | readonly number[] = number | readonly number[]> = Base.Root.Props<Value>
  export type ChangeEventReason = Base.Root.ChangeEventReason
  export type ChangeEventDetails = Base.Root.ChangeEventDetails
  export type CommitEventReason = Base.Root.CommitEventReason
  export type CommitEventDetails = Base.Root.CommitEventDetails
}
export const Label: typeof Base.Label = /*#__PURE__*/ (() => Base.Label)()
export declare namespace Label {
  export type State = Base.Label.State
  export type Props = Base.Label.Props
}
export const Value: typeof Base.Value = /*#__PURE__*/ (() => wrapPart(Base.Value, 'nave-base-ui-slider-value'))()
export declare namespace Value {
  export type State = Base.Value.State
  export type Props = Base.Value.Props
}
export const Control: typeof Base.Control = /*#__PURE__*/ (() => wrapPart(Base.Control, 'nave-base-ui-slider-control'))()
export declare namespace Control {
  export type State = Base.Control.State
  export type Props = Base.Control.Props
}
export const Track: typeof Base.Track = /*#__PURE__*/ (() => wrapPart(Base.Track, 'nave-base-ui-slider-track'))()
export declare namespace Track {
  export type State = Base.Track.State
  export type Props = Base.Track.Props
}
export const Thumb: typeof Base.Thumb = /*#__PURE__*/ (() => wrapPart(Base.Thumb, 'nave-base-ui-slider-thumb'))()
export declare namespace Thumb {
  export type State = Base.Thumb.State
  export type Props = Base.Thumb.Props
}
export const Indicator: typeof Base.Indicator = /*#__PURE__*/ (() => Base.Indicator)()
export declare namespace Indicator {
  export type State = Base.Indicator.State
  export type Props = Base.Indicator.Props
}
